project:
  type: website

website:
  page-navigation: true
  search: false
  navbar:
    tools:
      - icon: github
        url: https://github.com/CogBrainHealthLab
      
    logo: "images/lablogowhitebgcropped.png"
    left:
      - href: index.qmd
        text: About us
      - href: team.qmd
        text: The team
      - href: pub.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: dataart.qmd
        text: Data Art
      - href: join.qmd
        text: Join the lab
      - href: participate.qmd
        text: Participate

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    fontsize: 12pt
    
editor: visual

